name: Renovate

on:
  # schedule: # <-- 여기를 주석 처리
  #   - cron: '0 0 * * 0'
  workflow_dispatch: # 수동으로 워크플로우를 실행할 수 있도록 추가 (이것만 남겨두면 됨!)

permissions:
  contents: write
  pull-requests: write

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2

      - name: Run Renovate
        uses: renovatebot/github-action@v44.2.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          configurationFile: renovate.json
          repositories: ${{ github.repository }}
        env:
          LOG_LEVEL: 'debug'